#undef PR_DELETE_SRC
#define PR_DELETE_SRC 0
#undef PR_RING_EQUAL
#define PR_RING_EQUAL 0
#undef PR_NUMBER_SIMPLE
#define PR_NUMBER_SIMPLE 0
#undef PR_NO_SORT
#define PR_NO_SORT 0
#undef PR_NAME
#define PR_NAME pr_Copy_NoREqual_NoNSimple_Sort
#include "polys/prCopyMacros.h"
#include "polys/prCopyTemplate.cc"

#undef PR_NO_SORT
#define PR_NO_SORT 1
#undef PR_NAME
#define PR_NAME pr_Copy_NoREqual_NoNSimple_NoSort
#include "polys/prCopyMacros.h"
#include "polys/prCopyTemplate.cc"


#undef PR_NUMBER_SIMPLE
#define PR_NUMBER_SIMPLE 1
#undef PR_NO_SORT
#define PR_NO_SORT 0
#undef PR_NAME
#define PR_NAME pr_Copy_NoREqual_NSimple_Sort
#include "polys/prCopyMacros.h"
#include "polys/prCopyTemplate.cc"

#undef PR_NO_SORT
#define PR_NO_SORT 1
#undef PR_NAME
#define PR_NAME pr_Copy_NoREqual_NSimple_NoSort
#include "polys/prCopyMacros.h"
#include "polys/prCopyTemplate.cc"



#undef PR_RING_EQUAL
#define PR_RING_EQUAL 1
#undef PR_NUMBER_SIMPLE
#define PR_NUMBER_SIMPLE 0
#undef PR_NO_SORT
#define PR_NO_SORT 0
#undef PR_NAME
#define PR_NAME pr_Copy_REqual_NoNSimple_Sort
#include "polys/prCopyMacros.h"
#include "polys/prCopyTemplate.cc"

#undef PR_NO_SORT
#define PR_NO_SORT 1
#undef PR_NAME
#define PR_NAME pr_Copy_REqual_NoNSimple_NoSort
#include "polys/prCopyMacros.h"
#include "polys/prCopyTemplate.cc"


#undef PR_NUMBER_SIMPLE
#define PR_NUMBER_SIMPLE 1
#undef PR_NO_SORT
#define PR_NO_SORT 0
#undef PR_NAME
#define PR_NAME pr_Copy_REqual_NSimple_Sort
#include "polys/prCopyMacros.h"
#include "polys/prCopyTemplate.cc"

#undef PR_NO_SORT
#define PR_NO_SORT 1
#undef PR_NAME
#define PR_NAME pr_Copy_REqual_NSimple_NoSort
#include "polys/prCopyMacros.h"
#include "polys/prCopyTemplate.cc"




#undef PR_DELETE_SRC
#define PR_DELETE_SRC 1
#undef PR_RING_EQUAL
#define PR_RING_EQUAL 0
#undef PR_NUMBER_SIMPLE
#define PR_NUMBER_SIMPLE 0
#undef PR_NO_SORT
#define PR_NO_SORT 0
#undef PR_NAME
#define PR_NAME pr_Move_NoREqual_NoNSimple_Sort
#include "polys/prCopyMacros.h"
#include "polys/prCopyTemplate.cc"

#undef PR_NO_SORT
#define PR_NO_SORT 1
#undef PR_NAME
#define PR_NAME pr_Move_NoREqual_NoNSimple_NoSort
#include "polys/prCopyMacros.h"
#include "polys/prCopyTemplate.cc"


#undef PR_NUMBER_SIMPLE
#define PR_NUMBER_SIMPLE 1
#undef PR_NO_SORT
#define PR_NO_SORT 0
#undef PR_NAME
#define PR_NAME pr_Move_NoREqual_NSimple_Sort
#include "polys/prCopyMacros.h"
#include "polys/prCopyTemplate.cc"

#undef PR_NO_SORT
#define PR_NO_SORT 1
#undef PR_NAME
#define PR_NAME pr_Move_NoREqual_NSimple_NoSort
#include "polys/prCopyMacros.h"
#include "polys/prCopyTemplate.cc"



#undef PR_RING_EQUAL
#define PR_RING_EQUAL 1
#undef PR_NUMBER_SIMPLE
#define PR_NUMBER_SIMPLE 0
#undef PR_NO_SORT
#define PR_NO_SORT 0
#undef PR_NAME
#define PR_NAME pr_Move_REqual_NoNSimple_Sort
#include "polys/prCopyMacros.h"
#include "polys/prCopyTemplate.cc"

#undef PR_NO_SORT
#define PR_NO_SORT 1
#undef PR_NAME
#define PR_NAME pr_Move_REqual_NoNSimple_NoSort
#include "polys/prCopyMacros.h"
#include "polys/prCopyTemplate.cc"


#undef PR_NUMBER_SIMPLE
#define PR_NUMBER_SIMPLE 1
#undef PR_NO_SORT
#define PR_NO_SORT 0
#undef PR_NAME
#define PR_NAME pr_Move_REqual_NSimple_Sort
#include "polys/prCopyMacros.h"
#include "polys/prCopyTemplate.cc"

#undef PR_NO_SORT
#define PR_NO_SORT 1
#undef PR_NAME
#define PR_NAME pr_Move_REqual_NSimple_NoSort
#include "polys/prCopyMacros.h"
#include "polys/prCopyTemplate.cc"





